version: '3.8'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: taskdb
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: taskpass
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    image: anshika1028/task-manager:latest
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: task_manager_db
      DB_USER: taskuser
      DB_PASSWORD: taskpass
    depends_on:
      - db

volumes:
  pgdata:
